CREATE TABLE [dbo].[Duration]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[Description] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Duration] ADD CONSTRAINT [PK__tmp_ms_x__3214EC071C5E9F0C] PRIMARY KEY CLUSTERED  ([Id]) ON [PRIMARY]
GO
