//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicDataTheClaimTrainDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int CompanyId { get; set; }
        public string StationFrom { get; set; }
        public string StationTo { get; set; }
        public System.TimeSpan ExpectedTime { get; set; }
        public System.TimeSpan ActualTime { get; set; }
        public string TicketUrl { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Person Person { get; set; }
    }
}
