//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicDataTheClaimTrainDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compensation
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int DurationId { get; set; }
        public int Percentage { get; set; }
        public int FormatId { get; set; }
        public string FinePrint { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Duration Duration { get; set; }
        public virtual Format Format { get; set; }
    }
}
