//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicDataTheClaimTrainDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TheClaimTrainDbEntities : DbContext
    {
        public TheClaimTrainDbEntities()
            : base("name=TheClaimTrainDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Claim> Claims { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<Compensation> Compensations { get; set; }
        public DbSet<Duration> Durations { get; set; }
        public DbSet<Format> Formats { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<Title> Titles { get; set; }
    }
}
